apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-deployment
  namespace: lms-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms
  template:
    metadata:
      labels:
        app: lms
    spec:
      containers:
      - name: lms-app
        image: 688428951895.dkr.ecr.ap-southeast-1.amazonaws.com/lms-app:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "400Mi"
          requests:
            cpu: "0.25"
            memory: "350Mi"
        env:
        - name: DB_HOST
          value: "database-ukmshape.cj3gorfkfzca.ap-southeast-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "ecourse"
        - name: DB_USERNAME
          value: admin
        - name: DB_PASSWORD
          value: ukmshapeUKMAWS  
---
apiVersion: v1
kind: Service
metadata:
  name: lms-service
  namespace: lms-system
spec:
  selector:
    app: lms
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer