<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['next_link'] = 'Next <i class="ti-angle-right"></i>';
$config['prev_link'] = '<i class="ti-angle-left"></i> Prev';
$config['first_link'] = '<i class="ti-angle-double-left"></i> Start';
$config['last_link'] = 'Last <i class="ti-angle-double-right"></i>';
$config['full_tag_open'] = '<ul class="pagination">';
$config['full_tag_close'] = '</ul>';
$config['num_tag_open'] = '<li>';
$config['num_tag_close'] = '</li>';
$config['cur_tag_open'] = '<li class="active"><a href="javascript:void();">';
$config['cur_tag_close'] = '</a></li>';
$config['prev_tag_open'] = '<li class="previous">';
$config['prev_tag_close'] = '</li>';
$config['next_tag_open'] = '<li class="next">';
$config['next_tag_close'] = '</li>';
$config['last_tag_open'] = '<li class="next">';
$config['last_tag_close'] = '</li>';
$config['first_tag_open'] = '<li class="previous">';
$config['first_tag_close'] = '</li>';
